### ISSUE TITLE
Any pretrained weight?

### ISSUE THREAD

**Issue by LeeKyungwook** [koushiksrivats/FLIP#1]
Thanks for sharing great work.

is there any plans to share pretrained weight??

**Comment by koushiksrivats** [comment]
Hi 
Thank you for your interest in our work.

As you might have seen from the paper, we have run each of our experiment 5 times and report the average scores.
So naturally, the combined number of weight files across all the experiments is a lot and takes up a lot of storage. Hence, we currently haven't uploaded our weight files.

We'll be looking into an efficient solution for uploading the weight files.

**Comment by PetrDvoracek** [comment]
Hi @koushiksrivats ,

If storage is the only problem for sharing weights with community, I could provide you a space on my google drive where you could upload it for free.

Please let us know if this is feasible for you, sharing the pretrained weights would help community a lot.

Thank you.

**Comment by koushiksrivats** [comment]
Hi @PetrDvoracek 

Thank you for your generous offer to provide free storage.

Certainly as mentioned in this [response](https://github.com/koushiksrivats/FLIP/issues/1#issuecomment-1757457682) uploading weight files for all the trained models (7 experiments (M-C-I-O-W-C-S) x 5 runs (per experiment) x 2 settings (0-shot and 5-shot) = 70 models] was the initial challenge.

However, the primary issue now is that I do not have access to the machine I used to train these models. Hence as mentioned in this [issue](https://github.com/koushiksrivats/FLIP/issues/7#issuecomment-1999283175), I am arranging the weight files (training from my end) for the 7 experiments in 0-shot setting and will upload the checkpoints corresponding to the best runs (for each of the 7 experiments) in a few days.

@LeeKyungwook @TranThanh96 I will reopen this issue and I shall update once the checkpoints are uploaded.

Thanks for your understanding.

**Comment by koushiksrivats** [comment]
Hi @LeeKyungwook @TranThanh96 @PetrDvoracek 

The checkpoint files for M-C-I-O-W-C-S, for both the 0-shot and 5-shot settings, can be found [here in model zoo](https://github.com/koushiksrivats/FLIP/blob/main/docs/model_zoo.md).
