### ISSUE TITLE
Dataloader Error

### ISSUE THREAD

**Issue by naeun0620** [koushiksrivats/FLIP#2]
Nice work and thanks for sharing!

I have a question about the code. what is `fake_shot.txt` for and where is it? 
It gives the following error.
```
FLIP/utils/utils.py", line 65, in sample_frames
    for i in open(dataroot + dataset_name + '_fake_shot.txt').readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'data/MCIO/txt/msu_fake_shot.txt
```
Thanks!

**Comment by koushiksrivats** [comment]
Thank you for your interest in our work.

**What is {fake/real}_shot.txt for ?**
To extend our work to the few-shot setting (5-shot in the experiments), we follow the [few_shot_fas](https://github.com/hhsinping/few_shot_fas/tree/main) repo and use the samples in {fake/real}_shot.txt during training.

**Where is it ?**
Thanks for highlighting this. It is now added to the txt files inside each benchmark in the [data](https://github.com/koushiksrivats/FLIP/tree/main/data) folder.
