### ISSUE TITLE
Cannot reproduce the performance in the paper

### ISSUE THREAD

**Issue by naeun0620** [koushiksrivats/FLIP#4]
Hello, thanks for sharing the impressive work!

I have been trying to reproduce the performance of FLIP-MCL.
I preprocessed the datasets in Protocol 1 and ran `train_flip_mcl.py`. 
However, the average HTER in protocol 1 is about two times bigger than the numbers in the paper. 

Can you give any suggestions or ideas that I can change? 

Here is the result I got by running `python train_flip_mcl.py --config O`
```
Run, HTER, AUC, TPR@FPR=1%
0,7.5833047062864996,97.71310791578742,60.985915492957744
1,8.581488933601609,96.89564214555627,46.76056338028169
2,7.74083525543505,97.56622662806103,51.54929577464789
3,8.301271040879424,97.38840359228543,61.12676056338028
4,7.635569514648869,97.55994503607008,58.028169014084504
Mean,7.968493890170292,97.42466506355206,55.69014084507042
Std dev,0.39938486613099317,0.28380266685835653,5.656012560076761
```
Thanks!

**Comment by koushiksrivats** [comment]
Hi
Thank you for your interest in our work.

Could you please share/confirm the following information to help me understand your issue better ?

1. Are you using the same conda environment created using this [environment.yml file](https://github.com/koushiksrivats/FLIP/blob/main/environment.yml) ?
2. Which CUDA driver version are you using ? (eg: 9.1/ 10.1/ 10.2)
3. Could you share one image per dataset from protocol-1 for me to see how your pre-processed data looks ?

**Comment by naeun0620** [comment]
Thanks for your fast reply! 

1. I am not using the same conda environment, but I will try with [environment.yml file](https://github.com/koushiksrivats/FLIP/blob/main/environment.yml) again. thanks!
2. My cuda version is 11.5. 
3. This is one image per a dataset of pre-processed data. I didn't resize them because the [dataloader code](https://github.com/koushiksrivats/FLIP/blob/main/utils/dataset.py#L93) resizes them. 

| M | I | C | O |
| ------------- | ------------- |------------- |------------- |
| ![M_attack_client001_android_SD_ipad_video_scene01_frame1](https://github.com/koushiksrivats/FLIP/assets/42523928/809b99d1-178b-49d4-80a3-d894751826fb)  | ![I_fixed_attack_highdef_client009_session01_highdef_photo_controlled_frame1](https://github.com/koushiksrivats/FLIP/assets/42523928/02af61b9-ac8c-44cf-9665-547f86af1181)  | ![C_10_3_frame1](https://github.com/koushiksrivats/FLIP/assets/42523928/e3bca542-eae2-4f24-b011-f407ef9695b9) | ![O_1_1_37_2_frame0](https://github.com/koushiksrivats/FLIP/assets/42523928/91b3b069-6046-41b8-a5b8-63af1d9bbb49) |

**Comment by koushiksrivats** [comment]
1. Sure
2. Okay. The version I used was 10.1. 
3. Looking at the images, the issue you are facing is because the images seems to be pre-processed differently. Please follow the pre-processing steps from [here](https://github.com/koushiksrivats/FLIP/blob/main/docs/datasets.md#data-preprocessing---benchmark-1) and see if it solves your issue.

**Comment by naeun0620** [comment]
While pre-processing, did you align faces with 5 point landmarks by rotating the image?

**Comment by naeun0620** [comment]
Apparently, it was the data pre-processing problem. I could reproduce your result after following your pre-processing steps. Thanks for answering!

**Comment by Elijah-Yi** [comment]
Hi, I still cannot achieve the results in the paper by following the preprocessing code provided. Can you share your data preprocessing and image frame selection code? thank you!
