### ISSUE TITLE
Could you share the pre-trained weight that necessary for successfully running the inference process of your project?

### ISSUE THREAD

**Issue by JohnCarpenter2** [koushiksrivats/FLIP#7]
Thank you for open-sourcing this wonderful work. We are researchers from different fields and would like to leverage your work for our own works. However, we are not well-versed in FAS, so it would be quite challenging for us to obtain the datasets and train the model from scratch.

We are not interested in obtaining all the pre-trained weights in the paper. Our goal is simply to acquire the specific weight necessary for successfully running the inference process of your project.

Could you share the pre-trained weight that necessary for successfully running the inference process of your project?

Thank you very much.

**Comment by PetrDvoracek** [comment]
Hi, I would also appreciate if you would share at least some weights from the paper.

**Comment by koushiksrivats** [comment]
Hi 
Thank you for your interest in our work.

I currently do not have access to any of the weight files. 

I shall arrange and upload them in a few days.

**Comment by koushiksrivats** [comment]
Hi @JohnCarpenter2 @PetrDvoracek 

The weight files for M-C-I-O-W-C-S, in both the 0-shot and 5-shot settings, can be found [here in model zoo](https://github.com/koushiksrivats/FLIP/blob/main/docs/model_zoo.md).
